### ISSUE TITLE
installs under Python 3, but doesn't work

### ISSUE THREAD

**Issue by matteodellamico** [slezica/python-frozendict#5]
Hi,

frozendict doesn't work in Python 3. The first problem I find is

    Traceback (most recent call last):
      File "./MC_experiment.py", line 13, in <module>
        items = set(random.sample(items, 1000))
      File "/usr/local/lib/python3.4/dist-packages/frozendict/__init__.py", line 26, in __hash__
        self.__hash = reduce(operator.xor, map(hash, self.iteritems()), 0)
    NameError: name 'reduce' is not defined

(of course fixing this one should be trivial)

Is Py3 supposed to be supported?

**Comment by wbolster** [comment]
fwiw:

```python
try:  # Python 3
    from functools import reduce
except ImportError:  # Python 2
    pass
```

**Comment by lurch** [comment]
No need for the try / catch - Python2 already has functools.reduce https://docs.python.org/2/library/functools.html#functools.reduce

And #3 fixed Python3 support, so this issue can probably be closed?

**Comment by ppolewicz** [comment]
@slezica this issue can be closed now
